#+TITLE:  Programmiersprachen:  Glossar

*** C++
    /C++/ ist eine objektorientierte Programmiersprache, deren
    Entwicklung Ende der 70er Jahre mit /C with Classes/ begann.  Die
    Sprache wird ständig weiterentwickelt, wobei der zukünftige
    Standard /C++20/ sein wird.  /C++/ bietet eine /direct map to
    hardware/ und /zero-overhead abstraction/, eignet sich also
    besonders gut für performancekritische Anwendungen.
*** Quellcode
    /Quellcode/ ist menschenlesbarer und i.d.R. auch vom Menschen
    geschriebener Code.  Je nach Programmiersprache stellt der
    Quellcode eine verschiedene Abstraktion der Hardwareebene dar.
*** Compiler
    Der /Compiler/ übersetzt den Quellcode in Maschinensprache und
    stellt sog. /Objektcode/ her.
*** Objektcode
    Der /Objektcode/ ist der vom Compiler generierte Maschinencode zu
    jeder Quellcode-Datei.
*** Linker
    Der /Linker/ fügt die Objektdateien in einer einzigen ausführbaren
    Datei zusammen.
*** Ausführbare Datei
    Die /Ausführbare Datei/ ist das Resultat des Linkens.  Sie stellt
    das fertige Programm dar, das auch ohne, dass der Quellcode
    verfügbar ist, ausgeführt und verwendet werden kann.  Verschiedene
    Betriebssysteme haben verschiedene Formate für Ausführbare
    Binärdateien.
*** ~main()~
    Die ~main~-Funktion ist der Einstiegspunkt in das Programm.  Sie
    kann ggf. Kommandozeilenparameter übergeben bekommen und gibt als
    ~int~ einen Exit Code zurück.
*** ~#include~
    ~#include "foo.bar"​~ ist eine Anweisung für den Präprozessor, die
    Datei ~foo.bar~ an dieser Stelle einzufügen.  Die Anweisung wird
    genutzt, um Header einzubinden.  Header aus auf dem System
    installierten Bibliotheken werden so eingebunden:
    ~#include <baz>~.
*** Kommentar
    Ein Kommentar wird vom Compiler ignoriert und dient dazu, den Code
    zu dokumentieren.
    #+BEGIN_SRC cpp
// Dies ist ein einzeiliger Kommentar.

/* Dieser Kommentar
   erstreckt sich über
   mehrere Zeilen. */
    #+END_SRC
*** Header
    Eine /Header/-Datei enthält Methodendeklarationen und
    Klassendefinitionen (wobei die Membervariablen und -funktionen
    deklariert werden).  In Headern werden also Schnittstellen
    festgelegt, deren Ausprägung dann in anderen Dateien implementiert
    wird.  Mit /C++20/-Modulen ist eine solche Trennung nicht mehr
    nötig.
*** Programm
    Allgemeiner Begriff, der eine Menge Source-Code und/oder
    ausführbare Dateien bezeichnet, die i.d.R. einen
    anwenderorientierten Zweck erfüllen.
*** Ausgabe
    Ein Programm gibt Daten über eine Shell, grafische Oberfläche,
    Datei etc.  an Nutzer oder andere Software weiter.
*** ~std::cout~
    Der Standard-Ausgabe-Stream, über den Ausgaben in die Shell
    gegeben werden.
*** ~std::cin~
    Der Standard-Eingabe-Stream, der manuelle Eingaben in die Shell
    erfasst oder Daten, die per Pipe o.Ä. an das Programm geleitet werden.
*** ~<<~ und ~>>~
    Die beiden Operatoren schreiben Strings.  Mit ~std::cout << "A"~
    wird ein String in den /stdout/ geschrieben, mit ~std::cin >> foo~
    ein String vom /stdin/ in die Variable ~foo~.
*** Funktion
    Eine Funktion ist ein Ablauf von Instruktionen, der ggf. Eingaben
    bekommt und ggf. eine Ausgabe zurückgibt.
*** Funktionssignatur
    Mit der Signatur einer Funktion in C++ wird der Rückgabetyp und
    die Typen der Parameter einer Funktion bezeichnet.  Die Funktion
    ~int gcd(int a, int b)~ nimmt zwei Integer und gibt einen Integer
    zurück.
*** Typ, Typkonvertierung, ~const~, Variable, Name, Wert
    Siehe [[https://github.com/jakobbbb/programmiersprachen-aufgabe-1#aufgabe-14][Aufgabe 1.4]].
*** Initialisierung und Zuweisung
    Siehe [[https://github.com/jakobbbb/programmiersprachen-aufgabe-1#aufgabe-15][Aufgabe 1.5]].
*** Deklaration und Definition
    Siehe [[https://github.com/jakobbbb/programmiersprachen-aufgabe-1#aufgabe-16][Aufgabe 1.6]].
*** Gültigkeitsbereich
    Siehe [[https://github.com/jakobbbb/programmiersprachen-aufgabe-1#aufgabe-17][Aufgabe 1.7]].
